### ISSUE TITLE
中国移动云空间

### ISSUE THREAD

**Issue by Angxb4cn** [qaiu/netdisk-fast-download#1]
大佬这个支持大文件上传下载，无需登录就可以下载，没有下载限制，能不能支持解析这个

无加密：链接：https://www.ecpan.cn/web/#/yunpanProxy?path=%2F%23%2Fdrive%2Foutside&data=06630f8402ba2a14539a1c57f18d64708gasn&isShare=1

加密：链接：https://www.ecpan.cn/web/#/yunpanProxy?path=%2F%23%2Fdrive%2Foutside&data=8af109ad858523145a5d296d12698a4cWN9cgJMcur&isShare=1
访问密码：WqIKZD

**Comment by qaiu** [comment]
嗯，这个可以考虑
