### ISSUE TITLE
奶牛快传

### ISSUE THREAD

**Issue by WhiteSevs** [qaiu/netdisk-fast-download#11]
奶牛快传链接有种格式是zip的
[https://goldrepo.cowtransfer.com/s/026a638795634b](https://goldrepo.cowtransfer.com/s/026a638795634b)
这种格式解析出来的data.firstFile里是空的，信息在data.firstFolder里，根据zipDownload判断，传个guid就可以获取下载链接了
https://cowtransfer.com/core/api/transfer/share/download?transferGuid=${guid}&fileId=

**Comment by qaiu** [comment]
已添加奶牛zip下载支持, 
接口https://cowtransfer.com/core/api/transfer/share/download?transferGuid={guid}&title={下载文件名} 
不能传文件id 否则返回403错误, 
另外需要一个title参数 否则生成默认文件名cowtransfer.zip
