### ISSUE TITLE
奶牛规则更新, 需要Refere header

### ISSUE THREAD

**Issue by qaiu** [qaiu/netdisk-fast-download#16]
doing

**Comment by qaiu** [comment]
加了防盗链
Referer: https://cowtransfer.com/

**Comment by gaoyunshu** [comment]
解析的链接迅雷能下  但是浏览器直接打不开   如何解决呢

**Comment by qaiu** [comment]
奶牛吗？需要浏览器插件添加header

**Comment by gaoyunshu** [comment]
是的  靠编程发请求里面倒是可以下了，这种看来需要专门做一个软件才能搞定  ，感谢   完美解决了

**Comment by qaiu** [comment]
> 是的  靠编程发请求里面倒是可以下了，这种看来需要专门做一个软件才能搞定  ，感谢   完美解决了
> 

是的，不过很多下载器都自带这种功能
