### ISSUE TITLE
小飞机解析500

### ISSUE THREAD

**Issue by jiangfu204** [qaiu/netdisk-fast-download#17]
2023-09-08 09:25:31.949 [34mINFO [0;39m -> [35m[       Router-9][0;39m [36m
c.q.l.c.interceptorImpl.LogStatistics   [0;39m : inserted log: id=3551616331792
91648, path=/json/parser?url=https://www.feijix.com/s/VZJH6fj, code=500

小飞机解析500请问这是官方的屏蔽了么

**Comment by qaiu** [comment]
![image](https://github.com/qaiu/netdisk-fast-download/assets/29825328/ee9d6011-91fb-41ee-9294-fe3a1e31b758)
没问题呀

**Comment by jiangfu204** [comment]
> 

服务器网页都是可以打开的，netdisk解析就报500，难道服务器被屏蔽了么

**Comment by jiangfu204** [comment]
2023-09-08 10:04:39.580 [34mINFO [0;39m -> [35m[       Router-1][0;39m [36m
c.q.l.c.interceptorImpl.LogStatistics   [0;39m : inserted log: id=3551714799203
00032, path=/json/parser?url=https://www.feijix.com/s/u6UUQinV, code=500
2023-09-08 10:09:16.287 [39mDEBUG[0;39m -> [35m[       Router-4][0;39m [36m
c.q.v.c.h.RouterHandlerFactory          [0;39m : The HTTP service request addre
ss information ===>path:/json/parser, uri:http://127.0.0.1:6400/json/parser?url=
https://www.feijix.com/s/u6UUQinV, method:GET
è¿›å…¥å‰ç½®æ‹¦æˆªå™¨1->/json/parser
2023-09-08 10:09:16.364 [1;31mERROR[0;39m -> [35m[      Router-10][0;39m [3
6mcn.qaiu.parser.impl.FjTool              [0;39m : è§£æžå¼‚å¸¸: https://api.fe
ijipan.com/ws/file/redirect?downloadId={fidEncode}&enable=1&devType=6&uuid={uuid
}&timestamp={ts}&auth={auth} æœªæ‰¾åˆ°é‡å®šå‘URL:
Server=nginx
Date=Fri, 08 Sep 2023 02:09:16 GMT
Content-Type=application/json;charset=UTF-8
Transfer-Encoding=chunked
Connection=keep-alive
Vary=Origin
Vary=Access-Control-Request-Method
Vary=Access-Control-Request-Headers

2023-09-08 10:09:16.372 [34mINFO [0;39m -> [35m[       Router-9][0;39m [36m
c.q.l.c.interceptorImpl.LogStatistics   [0;39m : inserted log: id=3551726408658
98496, path=/json/parser?url=https://www.feijix.com/s/u6UUQinV, code=500

请问是这个么

**Comment by qaiu** [comment]
是的，看样子应该被屏蔽了，试试直接打开分享能下载么

**Comment by jiangfu204** [comment]
网页下载也不行了，屏蔽了估计，麻烦大佬了
