### ISSUE TITLE
小飞机网盘解析异常

### ISSUE THREAD

**Issue by LiangCha01** [qaiu/netdisk-fast-download#19]
FjTool - 解析异常: [} 未找到重定向URL: Server=nginx Date=Sat, 16 Sep 2023 11:56:15 GMT Content-Type=application/json;charset=UTF-8 Transfer-Encoding=chunked Connection=keep-alive Vary=Origin Vary=Access-Control-Request-Method Vary=Access-Control-Request-Headers

**Comment by qaiu** [comment]
在线解析访问量太大了，IP被屏蔽
参考：#17
建议本地搭建，或者使用代理IP池

**Comment by yukaidi1220** [comment]
应该不是在线解析访问量太大了，小飞机下载大文件强制要求登陆了

**Comment by qaiu** [comment]
是的，和123一样，大文件都要强制登录了

**Comment by qaiu** [comment]
> 多大文件？为什么我下载200mb的文件都没有要登录呢
非VIP用户限制500M
![607d843b3e90f90c5ad2c9a3c909e40](https://github.com/qaiu/netdisk-fast-download/assets/29825328/1692d422-1333-45d9-9b12-a6c979427cc2)

**Comment by LiangCha01** [comment]
哈哈 1g以上就用百度云了

**Comment by LiangCha01** [comment]
我测试了下本地解析 json用网盘标识的方法
http(s)://your_host/网盘标识/分享key(@分享密码) 
这个方法并不能用 链接不到

**Comment by LiangCha01** [comment]
没有任何反应 就是网页访问不了 网络连接出错
我是我的网址然后加6400端口后面就是网盘标识 加key 没有反应 就
http(s)://your_host/parser?url=分享链接(&pwd=xxx)
这种的可以用

**Comment by qaiu** [comment]
> 没有任何反应 就是网页访问不了 网络连接出错
> 我是我的网址然后加6400端口后面就是网盘标识 加key 没有反应 就
> http(s)://your_host/parser?url=分享链接(&pwd=xxx)
> 这种的可以用

![Screenshot_2023-09-20-22-08-40-675_com.termux.jpg](https://github.com/qaiu/netdisk-fast-download/assets/29825328/363a8108-03d0-491e-84aa-60b4ab6528ca)

![Screenshot_2023-09-20-22-08-49-761_com.android.chrome.jpg](https://github.com/qaiu/netdisk-fast-download/assets/29825328/e1e767c9-e39f-4aab-a787-254b09487c81)

我本地测试OK

**Comment by qaiu** [comment]
http://127.0.0.1:6400/json/fj/FmpXLDg

**Comment by LiangCha01** [comment]
是我服务器单开一个run.bat的原因吗 我本地测试也可以了  服务器就不行

**Comment by qaiu** [comment]
> 是我服务器单开一个run.bat的原因吗 我本地测试也可以了  服务器就不行

服务器上看下日志

**Comment by LiangCha01** [comment]
嗯我去测试测试去

**Comment by LiangCha01** [comment]
研究明白了 会用了  好使了

**Comment by LiangCha01** [comment]
飞机分享的文件一直转圈进不去  难道是解析过多了吗

**Comment by qaiu** [comment]
> 飞机分享的文件一直转圈进不去  难道是解析过多了吗

正常，小飞机经常抽风

**Comment by LiangCha01** [comment]
想问一下该如何https这种的访问方式呢  http可以 https就访问出错

**Comment by qaiu** [comment]
> 想问一下该如何https这种的访问方式呢  http可以 https就访问出错

布署ssl证书

**Comment by LiangCha01** [comment]
部署了我是win服务器 是给ip域名部署证书吗？  我ip下的几个域名都有证书  但是其他网址正常用ssl  就加上6400端口后 https就访问不到了

**Comment by LiangCha01** [comment]
求解求解

**Comment by qaiu** [comment]
> 请让我用邮箱或者QQ联系您  这个问题让我很疑惑因为 本身网站是https类型 如果https网站加载http资源 就会无法访问，这就是我为什么要https访问

q 736226400

**Comment by LiangCha01** [comment]
服务器是可以访问到网盘的  好像没有被屏蔽呀  就是访问的有点慢才加载出分享文件网页
