### ISSUE TITLE
Windows 本地搭建无法访问

### ISSUE THREAD

**Issue by ArtHuge** [qaiu/netdisk-fast-download#23]
本地搭建好了 浏览器访问以下链接提示： 
http://127.0.0.1:6400/json/parser?url=https://pan.quark.cn/s/*************

ERR_CONNECTION_REFUSED

**Comment by qaiu** [comment]
查看下启动日志
正常会提示: 
{
code:500
count:0
data:null
msg:"未知分享类型"
success:false
timestamp:1699009357561
}
因为目前还不支持夸克盘
