### ISSUE TITLE
123盘解析异常

### ISSUE THREAD

**Issue by varm** [qaiu/netdisk-fast-download#24]
你好，不管是预览地址还是在本地启动服务都提示“S3keyFlag不能为空”
```json
{
  "code": 500,
  "msg": "YeTool - 解析异常: Ye: downURLJson返回值异常->{\"code\":400,\"message\":\"S3keyFlag不能为空\",\"data\":null}",
  "success": false,
  "count": 0,
  "data": null,
  "timestamp": 1699xxxx
}
```

**Comment by qaiu** [comment]
可能改规则了
- TODO

**Comment by qaiu** [comment]
![Screenshot_2023-11-05-22-46-07-231_com.android.chrome.jpg](https://github.com/qaiu/netdisk-fast-download/assets/29825328/b7c1c8bf-2c0c-4b63-a1a8-85ba1438ae2e)

预览地址测试能正常解析，规则应该没改，所以这个议题先关闭了，建议提供网盘分享地址这边试一下

**Comment by qaiu** [comment]
> ![Screenshot_2023-11-05-22-46-07-231_com.android.chrome.jpg](https://github.com/qaiu/netdisk-fast-download/assets/29825328/b7c1c8bf-2c0c-4b63-a1a8-85ba1438ae2e)
> 
> 预览地址测试能正常解析，规则应该没改，所以这个议题先关闭了，建议提供网盘分享地址这边试一下

测试分享地址是 https://www.123pan.com/s/iaKtVv-ICECd

**Comment by varm** [comment]
https://www.123pan.com/s/15oVVv-XHy1H.html，好像打开是文件夹的话就出现这个问题了

**Comment by qaiu** [comment]
> https://www.123pan.com/s/15oVVv-XHy1H.html 我测试了下，好像打开是文件夹的话就出现这个问题了

暂不支持解析文件夹

**Comment by varm** [comment]
> > https://www.123pan.com/s/15oVVv-XHy1H.html 我测试了下，好像打开是文件夹的话就出现这个问题了
> 
> 暂不支持解析文件夹

明白，谢谢！
