### ISSUE TITLE
在云盘解析预览站上解析测试的移动云盘链接，显示：未知分享类型，不知是近期移动云盘官方规则更改了？？

### ISSUE THREAD

**Issue by P3R5T7U9** [qaiu/netdisk-fast-download#26]
刚用qaiu大你在此仓库ReadME中所贴的云盘解析预览站，解析一移动云盘链接，但解析结果为：“未知分享类型”，具体报错截图如下：
![](https://i.ibb.co/3M5Lby7/IMG-20231118-073056.jpg)

再贴上我用来测试的移动云资源链接地址，如下：
https://caiyun.139.com/m/i?1N5BTdWzVijDb

感觉qaiu大你开发的这个云盘解析直链仓库，对移动云空间这个网盘的适配，是不是尚未适配“caiyun.139.com”这个域名？？还是说移动云官方早已对这个域名的直链解析限制严格，无法编写对应的直链解析代码？

麻烦qaiu大回复说明惹😖

**Comment by qaiu** [comment]
本身不支持移动云，但支持移动云空间，注意他们都是不是一个东西，你那个应该是移动和彩云

**Comment by qaiu** [comment]
移动云云空间官网是
https://www.ecpan.cn/

**Comment by P3R5T7U9** [comment]
> 本身不支持移动云，但支持移动云空间，注意他们都是不是一个东西，你那个应该是移动和彩云

其实我发完Issue后，到谷歌上搜索了解了下，和彩云网盘就是移动云盘的前身，看qaiu大你回复说这个云盘直链解析的预览站本身不支持移动云盘，不知是因为什么原因导致qaiu大你没办法对移动云盘进行直链解析的适配支持？？
(小声：猜测移动云官方很久前对直链接口做了限制，甚至比度盘限制还严，导致移动云的直链接口基本被“废弃”了？🤔)

**Comment by P3R5T7U9** [comment]
> 本身不支持移动云，但支持移动云空间，注意他们都是不是一个东西，你那个应该是移动和彩云

另外，近两天我一直在找可解析“caiyun.139.com”这个域的直链脚本，其实在翻到qaiu大你开发的这个多家云盘直链解析服务之前，也翻了其它一些相关仓库，看到几个多家云盘直链解析的油猴脚本托管仓库描述说支持任何域名的移动云盘，比如这个油猴脚本仓库：
https://github.com/hmjz100/Online-disk-direct-link-download-assistant

我在其仓库中直链解析JS脚本源码中，也确实看到支持“caiyun.139.com”这个域名，但我JS始终没入门，只是在源码中看到有彩云盘的域名，但不知源码中关于彩云盘的代码段是不是真的提供直链解析。。。

主要之前看到qaiu大你开发的多家云盘直链解析的这个仓库还提供在线解析预览服务，所以就先测试使用了，结果是我“想多了”，没想到移动云云空间和移动云盘还不是同一类云盘；

有个小小的请求，麻烦qaiu大之后有时间翻阅下我在上面所发号称“支持解析彩云盘直链”的油猴脚本源码，如果qaiu大觉得相关解析源码切实可行，且移植难度不是很大的话，我在此建议qaiu大在日后的新版中可考虑增加对和彩云盘资源直链解析的支持😖
(再次小声：因为我在一些小众gal游戏分享&交流的论坛上，经常看到不少网友分享资源都是以和彩云盘链接形式分享)

**Comment by qaiu** [comment]
这个建议不错，不过之前也考虑过 好像因为和彩云不支持免登录下载 所以没做
