### ISSUE TITLE
建议加入随机ip和数据缓存策略

### ISSUE THREAD

**Issue by renwfy** [qaiu/netdisk-fast-download#29]
同一个链接解析，建议加入缓存策略。

**Comment by qaiu** [comment]
感谢您的建议，缓存已经考虑在加了，有些网盘也必须依赖缓存的，像联想乐云，有解析次数限制(100次)，加入缓存，一个直链有效期一般是两天，这样一个分享链接就能用200天了，其他网盘直链有效期还需要都验证一下，统一加

**Comment by huolanyun** [comment]
我们安装的是调用你api的客户端是吧，那不是和网页调用没区别吗

**Comment by renwfy** [comment]
> 我们安装的是调用你api的客户端是吧，那不是和网页调用没区别吗

自己服务器部署！

**Comment by qaiu** [comment]
缓存机制已加入,默认缓存59分钟, 各类网盘的直链有效期不同, 需要慢慢验证, lz.qaiu.top 已部署缓存版本, 如果某些缓存链接过期失效, 需要调整缓存时长.
