### ISSUE TITLE
小飞机一直好好的，突然这样了

### ISSUE THREAD

**Issue by 616734202** [qaiu/netdisk-fast-download#32]
{"code":500,"msg":"FjTool - 解析异常: https://api.feijipan.com/ws/file/redirect?downloadId={fidEncode}&enable=1&devType=6&uuid={uuid}&timestamp={ts}&auth={auth} 未找到重定向URL: \nServer=JSP3/2.0.14\nDate=Sat, 03 Feb 2024 08:48:13 GMT\nContent-Type=application/json;charset=UTF-8\nContent-Length=1192\nConnection=keep-alive\nVary=Origin\nVary=Access-Control-Request-Method\nVary=Access-Control-Request-Headers\nX-M-Log=QNM:xs1174;SRCPROXY:xs1752;SRC:61;SRCPROXY:61;QNM3:62\nX-M-Reqid=YEAAAOeLk_sQTrAX\nX-Qnm-Cache=RawProxy\nOhc-Cache-HIT=bdcmcache78 [1]\nOhc-File-Size=1192\nX-Cache-Status=MISS\n","success":false,"count":0,"data":null,"timestamp":1706950093884}

**Comment by qaiu** [comment]
参考#9
一般是解析次数过多ip被拉黑导致的
