### ISSUE TITLE
什么时候搞下夸克的直链下载，不用登录就可以下载文件

### ISSUE THREAD

**Issue by LimitBreaker01** [qaiu/netdisk-fast-download#36]
夸克给的空间又小，还需要氪金svip才有大空间。
什么时候搞下直接在分享链接页面获取直链从而进行下载。

**Comment by qaiu** [comment]
夸克/UC/阿里云盘之类的需要Cookie 后续考虑支持

**Comment by a535261661** [comment]
没有支持的必要，夸克UC都是需要Cookie才能下载，意义不大

**Comment by qaiu** [comment]
> 我觉得没有支持的必要，夸克UC都是需要Cookie才能下载，意义不大

正确的 肯定的 中立的 一针见血的
