### ISSUE TITLE
uc

### ISSUE THREAD

**Issue by puppet680** [qaiu/netdisk-fast-download#38]
这是一个分析的链接 https://drive.uc.cn/s/b0e9942be96b4#/list/share
这是uc的文件传输助手 https://fast.uc.cn

将连接重新组合后 https://fast.uc.cn/s/b0e9942be96b4#/list/share 可以直接下载文件，不需要登陆

**Comment by zbLiuLiu** [comment]
现在需要登录了，不过登录后依然能在线下
