### ISSUE TITLE
有没有一键安装，参考教程有一点模糊

### ISSUE THREAD

**Issue by huolanyun** [qaiu/netdisk-fast-download#39]
我好像安装好了，但是输入解析地址 出现错误，这个是安装后本地解析 还是调用你服务器的解析
如果是调用没意义，我本地可以是动态公网好换IP，如果是调用你服务器API，解析过多还是会解析不到

**Comment by qaiu** [comment]
执行安装脚本即可, 和一键安装没啥区别
安装后是本地解析, 解析过多问题 后续会加入缓存策略  能一定程度增加解析次数
另外部分网盘比如 移动空间 实测没有IP限制

**Comment by huolanyun** [comment]
本地解析的话，我第一次解析 理论是不应该解析不到，我刚装好，解析奶牛 和 小飞机 、123都获取不到地址

一键安装 不是要修改jdk17? 那一步不知道对不对

**Comment by huolanyun** [comment]
可以把jdk 打包到 里面直接修改配置文档，然后运行安装吗

**Comment by huolanyun** [comment]
看是运行了，单不知道对不对
反正解析不了
![1231](https://github.com/qaiu/netdisk-fast-download/assets/125254463/5519be92-7f32-472f-8f30-5100689bd420)

**Comment by huolanyun** [comment]
飞机盘解析异常
![fj](https://github.com/qaiu/netdisk-fast-download/assets/125254463/7237ca6c-4bbd-438f-9ac8-e7851f0dc0a8)

**Comment by qaiu** [comment]
文件是多大的?  大文件这个版本不支持

**Comment by qaiu** [comment]
看样子部署没问题  你可以试下蓝奏云

**Comment by qaiu** [comment]
好像 小飞机500M一下没问题你可以试下这个分享
https://share.feijipan.com/s/nMtCOXL
本地测试OK的
