### ISSUE TITLE
蓝奏云优享版500错误

### ISSUE THREAD

**Issue by Sakurai-Yukina** [qaiu/netdisk-fast-download#40]
蓝奏云优享版无法解析，显示500错误，大文件小文件都不能解析，使用公共解析和自行搭建也都500错误

**Comment by Sakurai-Yukina** [comment]
{"code":500,"msg":"IzTool - 解析异常: https://api.ilanzou.com/unproved/recommend/list?devType=6&devModel=Chrome&extra=2&shareId={shareId}&type=0&offset=1&limit=60 返回异常: {\"msg\":\"参数错误\",\"code\":-1}","success":false,"count":0,"data":null,"timestamp":1715495203887}

**Comment by qaiu** [comment]
厂商改规则了吗？我验证一下，请稍候
