### ISSUE TITLE
小飞机盘解析异常

### ISSUE THREAD

**Issue by 65658dsf** [qaiu/netdisk-fast-download#41]
{
  "code": 500,
  "msg": "FjTool - 解析异常: https://api.feijipan.com/ws/recommend/list?devType=6&devModel=Chrome&extra=2&shareId={shareId}&type=0&offset=1&limit=60 解析文件列表为空: {\"msg\":\"成功\",\"total\":0,\"code\":200,\"offset\":1,\"totalPage\":0,\"limit\":60,\"list\":[],\"status\":0}",
  "success": false,
  "count": 0,
  "data": null,
  "timestamp": 1716025628484
}

**Comment by qaiu** [comment]
参考#40 不要使用线上演示网站, 自己搭建服务, 另外500M以上小飞机和蓝奏云优享都不支持
