### ISSUE TITLE
小飞机好像解析不了了

### ISSUE THREAD

**Issue by Leozgu** [qaiu/netdisk-fast-download#43]
解析文件列表为空: {\"msg\":\"成功\",\"total\":0,\"code\":200,\"offset\":1,\"totalPage\":0,\"limit\":60,\"list\":[],\"status\":0}",
    "success": false,
    "count": 0,
    "data": null,
    "timestamp": 1716700464066
}

**Comment by Sakurai-Yukina** [comment]
同样的问题，求更新正式版
