### ISSUE TITLE
 求更Docker 一把梭😘

### ISSUE THREAD

**Issue by candies404** [qaiu/netdisk-fast-download#46]
手头没有可以测试docker服务器，毕竟1c2g的ecs性能太拉了 估计跑不动docker，过阵子应该可以测
😅😂😃😄😛

**Comment by candies404** [comment]
来催更了，哈哈 @qaiu

**Comment by qaiu** [comment]
> 来催更了，哈哈 @qaiu 

更新了宝塔布署教程，先参考一下
https://blog.qaiu.top/archives/netdisk-fast-download-bao-ta-an-zhuang-jiao-cheng
