### ISSUE TITLE
乐云的缓存有时效性

### ISSUE THREAD

**Issue by a419377389** [qaiu/netdisk-fast-download#57]
乐云的缓存有时效性，会过期但是链接不会更新

**Comment by a419377389** [comment]
> 乐云缓存链接应该是2天(48小时)后过期，之前验证过，没问题的。现在不行了么，具体时效性多久了解么？

现在具体多长时间没试，因为我上传的文件是22号19点上传的，而且从新解析还是上次的缓存链接，可能是不是需要加个判断或者第一次解析到下一次解析时间+48小时从新解析缓存呢

**Comment by qaiu** [comment]
> > 乐云缓存链接应该是2天(48小时)后过期，之前验证过，没问题的。现在不行了么，具体时效性多久了解么？
> 
> 现在具体多长时间没试，因为我上传的文件是22号19点上传的，而且从新解析还是上次的缓存链接，可能是不是需要加个判断或者第一次解析到下一次解析时间+48小时从新解析缓存呢

判断是有的，缓存到期肯定重新解析，但乐云有效期比较久，还没有严格测试过，但应该问题不大

**Comment by a419377389** [comment]
好了 好像第二次解析有延时
