### ISSUE TITLE
123云盘解析失败

### ISSUE THREAD

**Issue by jibukeshi** [qaiu/netdisk-fast-download#60]
123云盘解析失败，提示“S3keyFlag不能为空”。

接口返回内容如下

```json
{
  "code": 500,
  "msg": "YeTool - 解析异常: Ye: downURLJson返回值异常->{\"code\":400,\"message\":\"S3keyFlag不能为空\",\"data\":null}",
  "success": false,
  "count": 0,
  "data": null,
  "timestamp": 1727915061298
}
```

**Comment by qaiu** [comment]
建议提供解析失败的分享链接

**Comment by jibukeshi** [comment]
> 建议提供解析失败的分享链接

测试链接1：https://www.123pan.com/s/MjA7Vv-x0Ci.html 提取码：点赞投币

测试链接2：https://www.123pan.com/s/SDADVv-mzVxH

**Comment by qaiu** [comment]
![Screenshot_2024-10-04-10-35-47-140_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/e498a703-94c6-4410-93c3-acb81e708755)

123云盘
暂不支持分享文件夹解析，另外对于大文件也不支持

**Comment by qaiu** [comment]
或许分享单个文件然后分享者开通vip才不会有流量限制
