### ISSUE TITLE
老哥 能不能加这个的解析

### ISSUE THREAD

**Issue by a419377389** [qaiu/netdisk-fast-download#63]
https://zenvideo.qq.com/view/detail/2q9ndzb2uxfvcxsmtos4801

这个也可以玩，搞一个

**Comment by qaiu** [comment]
这个怎么玩，微信小程序？

**Comment by a419377389** [comment]
> 这个怎么玩，微信小程序？

好像玩不了，那个乐云的缓存怎么取消

**Comment by qaiu** [comment]
> > 这个怎么玩，微信小程序？
> 
> 好像玩不了，那个乐云的缓存怎么取消

app-dev.yml 缓存配置改为 le: -1

**Comment by a419377389** [comment]
> app-dev.yml

JSON输出那个能自定义吗？

**Comment by qaiu** [comment]
> > app-dev.yml
> 
> JSON输出那个能自定义吗？

不支持自定义json格式
