### ISSUE TITLE
蓝奏云优享版解析500错误

### ISSUE THREAD

**Issue by Sakurai-Yukina** [qaiu/netdisk-fast-download#71]
{
  "code": 500,
  "msg": "蓝奏云优享-iz - 解析异常: https://api.ilanzou.com/unproved/recommend/list?devType=6&devModel=Chrome&extra=2&shareId={shareId}&type=0&offset=1&limit=60 解析文件列表为空: {\"msg\":\"成功\",\"total\":0,\"code\":200,\"offset\":1,\"totalPage\":0,\"limit\":60,\"list\":[],\"status\":0}",
  "success": false,
  "count": 0,
  "data": null,
  "timestamp": 1731753490962
}

疑似厂商api又有变动？大佬有空的时候麻烦看一眼非常感谢！

**Comment by Sakurai-Yukina** [comment]
分享链接，https://www.ilanzou.com/s/NAgDbIx，无密码，公用解析和自行搭建均有错误

**Comment by qaiu** [comment]
正在处理

**Comment by Sakurai-Yukina** [comment]
最新情况，小飞机网盘和QQ邮箱也挂掉了，另外求大佬更新发行版，万分感谢！

**Comment by qaiu** [comment]
> 最新情况，小飞机网盘和QQ邮箱也挂掉了，另外求大佬更新发行版，万分感谢！

qq邮箱失效了么，我试了一下可以，请提供一下分享链接
