### ISSUE TITLE
移动云盘解析失败

### ISSUE THREAD

**Issue by pomeyo** [qaiu/netdisk-fast-download#72]
分享链接
https://caiyun.139.com/m/i?1A5ChGVCMVwkG
  分享密码
8rtV
 

解析结果:
copy
{
code:500
count:0
data:null
msg:"其他网盘-other - 解析异常: 暂未实现, 敬请期待"
success:false
timestamp:1731857129534
} 
估计是移动云更新链接了  识别不出来

**Comment by qaiu** [comment]
支持移动云云空间，不支持和彩云，这一点要清楚
139是和彩云

**Comment by pomeyo** [comment]
噢噢噢噢 这样啊  感谢大佬解答
