### ISSUE TITLE
蓝奏优享依然无法使用

### ISSUE THREAD

**Issue by stillms** [qaiu/netdisk-fast-download#77]
之前看您已经修复蓝奏优享版，但是我在qaiu和自己搭建仍然无法解析

**Comment by qaiu** [comment]
感谢反馈，目前演示地址因解析量过大IP可能已经被禁，如果自建服务依然无法使用可能是IP问题。目前测试阿里云，腾讯云的IP无法解析蓝奏优享和小飞机，天翼云好像可以，
下一步考虑接入IP代理池

**Comment by qaiu** [comment]
已经可以了, 需要添加IP代理配置, 通过搭建https://github.com/nfd-parser/nfd-proxy可以提供代理服务
app-dev.yml配置参考如下
```
  - panTypes: fj,ye,iz
    type: http # 支持http/socks4/socks5
    host: xxx
    port: xxx
    username: xxx
    password: xxx
```
