### ISSUE TITLE
你好123 云盘失效了

### ISSUE THREAD

**Issue by ImYoyoData** [qaiu/netdisk-fast-download#9]
{
code:500
count:0
data:null
msg:"Ye: downURLJson返回值异常->{"code":401,"message":"请登录后下载","data":null}"
success:false
timestamp:1691582818668

返回这个 这个是根据您的测试官方网来的

**Comment by qaiu** [comment]
待修复

**Comment by qaiu** [comment]
123的API导致的问题 /b/api/share->/a/api/share
https://lz.qaiu.top 部署完成
